// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Item = 2,
  Group = 3,
  Number = 4,
  String = 5,
  Keyword = 6,
  Identifier = 7,
  Operator = 8,
  LineComment = 9,
  BlockComment = 10
