// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,to:42, in:44, and:46, not:48, or:50, xor:52, mod:54}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!vQVQPOOO!ZQPO'#C_O!bQPO'#C_O!iQPO'#C_OOQO'#Cb'#CbOOQO'#C^'#C^OOQO'#Cg'#CgQVQPOOOOQO,58y,58yO!pQPO,58yO!wQPO,58yO#OQPO,58yOOQO-E6e-E6eOOQO1G.e1G.e",
  stateData: "#V~O^OS~OSTOTTOVTOWTOXTOYTO_POaQOcROeSOfSOgSOhSOiSOjSOkSO~O`WO~PVObWO~PVOdWO~PVO`]O~PVOb]O~PVOd]O~PVO",
  goto: "!T[PP]gPPgPPPPqaUOPQRVXYZaTOPQRVXYZQVOQXPQYQQZRX[VXYZ",
  nodeNames: "⚠ Program Item Group Number String Keyword Identifier Operator LineComment BlockComment",
  maxTerm: 27,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ".V~RpXY#VYZ#V]^#Vpq#Vqr#hrs#ust$juv#pvw#pwx'Oxy([yz(az{#p{|#p}!O#p!O!P(f!P!Q#p!Q!R(x!R![+R!^!_,b!_!`,u!`!a,{!c!}-`!}#O-q#P#Q-v#Q#R#p#R#S-`#T#o-`#o#p-{#p#q#p#q#r.Q#r#s#p~#[S^~XY#VYZ#V]^#Vpq#V~#mPW~!_!`#p~#uOW~~#xUOY#uZr#urs$[s;'S#u;'S;=`$d<%lO#u~$aPT~rs#u~$gP;=`<%l#u~$mUOY%PZ#o%P#o#p%h#p;'S%P;'S;=`%b<%lO%P~%USX~OY%PZ;'S%P;'S;=`%b<%lO%P~%eP;=`<%l%P~%kVOs%hst&Qt#q%h#q#r&o#r;'S%h;'S;=`&i<%lO%h~&TTO#q%h#q#r&d#r;'S%h;'S;=`&i<%lO%h~&iOY~~&lP;=`<%l%h~&rSOs%ht;'S%h;'S;=`&i<%lO%h~'TUW~OY'gZw'gwx'|x;'S'g;'S;=`(U<%lO'g~'jUOY'gZw'gwx'|x;'S'g;'S;=`(U<%lO'g~(RPT~wx'g~(XP;=`<%l'g~(aO_~~(fO`~~(iTz{#p{|#p}!O#p!P!Q#p#Q#R#p~(}XS~!O!P)j!Q![+R!f!g*[!g!h*[#W#X*[#X#Y*[#]#^*|#^#_*|#l#m+p~)mP!Q![)p~)uVS~!Q![)p!f!g*[!g!h*[#W#X*[#X#Y*[#]#^*|#^#_*|~*_R{|*h}!O*h!Q![*n~*kP!Q![*n~*sRS~!Q![*n#]#^*|#^#_*|~+ROS~~+WWS~!O!P)j!Q![+R!f!g*[!g!h*[#W#X*[#X#Y*[#]#^*|#^#_*|~+sR!Q![+|!c!i+|#T#Z+|~,RTS~!Q![+|!c!i+|#T#Z+|#]#^*|#^#_*|~,gQW~!^!_,m!_!`#p~,rPW~!^!_#p~,xP!_!`#p~-QQW~!_!`#p!`!a-W~-]PW~!`!a#p~-eSV~!Q![-`!c!}-`#R#S-`#T#o-`~-vOa~~-{Ob~~.QOc~~.VOd~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 7, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
